# Generated by Django 5.2.9 on 2026-01-06 00:26

import apps.common.models
import django.contrib.auth.models
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if the record is soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of soft deletion.', null=True)),
                ('email', models.EmailField(db_index=True, help_text="User's email address.", max_length=254, null=True, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text="User's phone number.", max_length=128, null=True, region=None, unique=True)),
                ('avatar', models.ImageField(default='default.jpg', help_text="User's profile picture.", upload_to='avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True, help_text="User's biography.")),
                ('country', models.CharField(blank=True, db_index=True, help_text="User's country.", max_length=100)),
                ('state', models.CharField(blank=True, help_text="User's state.", max_length=100)),
                ('city', models.CharField(blank=True, help_text="User's city.", max_length=100)),
                ('address', models.CharField(blank=True, help_text="User's address.", max_length=255)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='client', help_text="User's role in the system.", max_length=20)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('google', 'Google')], default='email', help_text='Authentication provider used.', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether the user is verified.')),
                ('pid', models.CharField(help_text='Unique identifier.', max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='authentication_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='authentication_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Unified User',
                'verbose_name_plural': 'Unified Users',
                'indexes': [models.Index(fields=['email', 'role'], name='authenticat_email_19147e_idx'), models.Index(fields=['phone', 'role'], name='authenticat_phone_532574_idx')],
            },
            bases=(models.Model, apps.common.models.HardDeleteMixin),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
